/**
 * bytewords.js
 * 
 * Copyright © 2020 Foundation Devices, Inc.
 * Licensed under the "BSD-2-Clause Plus Patent License"
 */

import { crc32Bytes, partition } from './utils.js';

const BYTEWORDS = 'ableacidalsoapexaquaarchatomauntawayaxisbackbaldbarnbeltbetabiasbluebodybragbrewbulbbuzzcalmcashcatschefcityclawcodecolacookcostcruxcurlcuspcyandarkdatadaysdelidicedietdoordowndrawdropdrumdulldutyeacheasyechoedgeepicevenexamexiteyesfactfairfernfigsfilmfishfizzflapflewfluxfoxyfreefrogfuelfundgalagamegeargemsgiftgirlglowgoodgraygrimgurugushgyrohalfhanghardhawkheathelphighhillholyhopehornhutsicedideaidleinchinkyintoirisironitemjadejazzjoinjoltjowljudojugsjumpjunkjurykeepkenokeptkeyskickkilnkingkitekiwiknoblamblavalazyleaflegsliarlimplionlistlogoloudloveluaulucklungmainmanymathmazememomenumeowmildmintmissmonknailnavyneednewsnextnoonnotenumbobeyoboeomitonyxopenovalowlspaidpartpeckplaypluspoempoolposepuffpumapurrquadquizraceramprealredorichroadrockroofrubyruinrunsrustsafesagascarsetssilkskewslotsoapsolosongstubsurfswantacotasktaxitenttiedtimetinytoiltombtoystriptunatwinuglyundouniturgeuservastveryvetovialvibeviewvisavoidvowswallwandwarmwaspwavewaxywebswhatwhenwhizwolfworkyankyawnyellyogayurtzapszerozestzinczonezoom';

let WORD_ARRAY = null;

function decodeWord(word, wordLen) {
  if (word.length !== wordLen) {
    throw new Error('Invalid Bytewords.');
  }

  const dim = 26;

  // Since the first and last letters of each Byteword are unique,
  // we can use them as indexes into a two-dimensional lookup table.
  // This table is generated lazily.
  if (WORD_ARRAY === null) {
    WORD_ARRAY = new Array(dim * dim).fill(-1);

    for (let i = 0; i < 256; i++) {
      const bytewordOffset = i * 4;
      const x = BYTEWORDS.charCodeAt(bytewordOffset) - 'a'.charCodeAt(0);
      const y = BYTEWORDS.charCodeAt(bytewordOffset + 3) - 'a'.charCodeAt(0);
      const arrayOffset = y * dim + x;
      WORD_ARRAY[arrayOffset] = i;
    }
  }

  // If the coordinates generated by the first and last letters are out of bounds,
  // or the lookup table contains -1 at the coordinates, then the word is not valid.
  const x = word[0].toLowerCase().charCodeAt(0) - 'a'.charCodeAt(0);
  const y = (word.length === 4 ? word[3] : word[1]).toLowerCase().charCodeAt(0) - 'a'.charCodeAt(0);
  
  if (!(0 <= x && x < dim && 0 <= y && y < dim)) {
    throw new Error('Invalid Bytewords.');
  }

  const offset = y * dim + x;
  const value = WORD_ARRAY[offset];
  if (value === -1) {
    throw new Error('Invalid Bytewords.');
  }

  // If we're decoding a full four-letter word, verify that the two middle letters are correct.
  if (word.length === 4) {
    const bytewordOffset = value * 4;
    const c1 = word[1].toLowerCase();
    const c2 = word[2].toLowerCase();
    if (c1 !== BYTEWORDS[bytewordOffset + 1] || c2 !== BYTEWORDS[bytewordOffset + 2]) {
      throw new Error('Invalid Bytewords.');
    }
  }

  // Successful decode.
  return value;
}

function getWord(index) {
  const bytewordOffset = index * 4;
  return BYTEWORDS.slice(bytewordOffset, bytewordOffset + 4);
}

function getMinimalWord(index) {
  const bytewordOffset = index * 4;
  return BYTEWORDS[bytewordOffset] + BYTEWORDS[bytewordOffset + 3];
}

function encode(buf, separator) {
  const words = [];
  for (let i = 0; i < buf.length; i++) {
    words.push(getWord(buf[i]));
  }
  return words.join(separator);
}

function addCrc(buf) {
  const crcBuf = crc32Bytes(buf);
  const result = new Uint8Array(buf.length + crcBuf.length);
  result.set(buf);
  result.set(crcBuf, buf.length);
  return result;
}

function encodeWithSeparator(buf, separator) {
  const crcBuf = addCrc(buf);
  return encode(crcBuf, separator);
}

function encodeMinimal(buf) {
  let result = '';
  const crcBuf = addCrc(buf);
  for (let i = 0; i < crcBuf.length; i++) {
    result += getMinimalWord(crcBuf[i]);
  }
  return result;
}

function decode(s, separator, wordLen) {
  const buf = [];

  let words;
  if (wordLen === 4) {
    words = s.split(separator);
  } else {
    words = partition(s, 2);
  }

  for (const word of words) {
    buf.push(decodeWord(word, wordLen));
  }

  if (buf.length < 5) {
    throw new Error('Invalid Bytewords.');
  }

  // Validate checksum
  const body = buf.slice(0, -4);
  const bodyChecksum = buf.slice(-4);
  const checksum = crc32Bytes(new Uint8Array(body));
  const checksumArray = Array.from(checksum);
  
  if (!bodyChecksum.every((val, i) => val === checksumArray[i])) {
    throw new Error('Invalid Bytewords.');
  }

  return new Uint8Array(body);
}

export const Bytewords_Style_standard = 1;
export const Bytewords_Style_uri = 2;
export const Bytewords_Style_minimal = 3;

export class Bytewords {
  static encode(style, bytes) {
    if (style === Bytewords_Style_standard) {
      return encodeWithSeparator(bytes, ' ');
    } else if (style === Bytewords_Style_uri) {
      return encodeWithSeparator(bytes, '-');
    } else if (style === Bytewords_Style_minimal) {
      return encodeMinimal(bytes);
    } else {
      throw new Error('Invalid style');
    }
  }

  static decode(style, str) {
    if (style === Bytewords_Style_standard) {
      return decode(str, ' ', 4);
    } else if (style === Bytewords_Style_uri) {
      return decode(str, '-', 4);
    } else if (style === Bytewords_Style_minimal) {
      return decode(str, 0, 2);
    } else {
      throw new Error('Invalid style');
    }
  }
}
